import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5

# opacity = 0.8
blur = true

decorations = "Buttonless"

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"

size = 20
