# Colors (Tokyo Night)
# Source https//github.com/zatchheems/tokyo-night-alacritty-theme

# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#C0CAF5'

# Normal colors
[colors.normal]
black   = '#32344a'
red     = '#F6768E'
green   = '#9ECE6B'
yellow  = '#E1AF69'
blue    = '#7AA2F7'
magenta = '#F7768E'
cyan    = '#449dab'
white   = '#A8B1D7'

# Bright colors
[colors.bright]
black   = '#444b6a'
red     = '#ff7a93'
green   = '#b9f27c'
yellow  = '#ff9e64'
blue    = '#7da6ff'
magenta = '#bb9af7'
cyan    = '#0db9d7'
white   = '#acb0d0'
